### PR TITLE
blog: nitty gritties of post creation

### PR DESCRIPTION
**Pull request by bnewbold**

### CODE REVIEW

**Review by emilyliu7321 — COMMENTED** [review]
This is amazing and will be super helpful to people picking up the API, thanks so much for the draft! @bnewbold 

I just made a bunch of changes, let me know what you think -- the high-level changes are restructuring the blog post to make it easier to read/follow for first-timers, and a couple tweaks/comments to the code snippets to make them easier to follow.

Is it possible to host a GitHub gist on the bluesky-social org instead of a personal account? Also, I prefer having references to specific accounts in the blog post default to @atproto.com instead of personal accounts -- mind updating those spots? 🙏

**Comment by bnewbold** [comment]
This is great! Thanks for the detailed edits.

I'd prefer to have the gist somewhere more official, but it confusingly isn't actually possible to create a new org gist, even though it is possible for them to exist for other orgs:
https://github.com/orgs/community/discussions/7923

Removed personal handles from examples, including re-generating the faceting example (ensuring counts still work). I didn't bother updating all the DIDs; those are staging DIDs anyways so shouldn't resolve in prod. If we think it is important I can re-run all the examples in staging from a special demo account or something, but doesn't seem worth the effort right now.

**Comment by bnewbold** [comment]
Open to other alternatives to personal github gist by the way. Could be a file somewhere in this repo, and link to the repo from the blog post?

**Comment by bnewbold** [comment]
I did a last round of code testing and fixed some of my own typos and missing imports.

I replaced `pds.bsky.social` in the leading CLI example. `pds.bsky.social` does technically seem to work, but I think `bsky.social` is the canonical PDS location/URL; for example all existing prod did-plc DID Documents point directly to `bsky.social`.

**Comment by emilyliu7321** [comment]
@bnewbold yeah i like the idea of moving the gist to a file in this repo! new folder for `scripts`? up to you how to implement

**Comment by bnewbold** [comment]
@emilyliu7321 moved it to this repo, under `examples/`. the link is a 404, but should work when this branch is merged. good to merge from my perspective!

**Pull request merged**
