### PR TITLE
lexicon spec doc bug fix: schema is ignored for non-JSON encodings

### PR DESCRIPTION
**Pull request by snarfed**
Minor fix. I think this is right, but feel free to correct me if not. Thanks in advance!

### CODE REVIEW

**Comment by bnewbold** [comment]
Thanks for the catch!

I think this might actually just be `optional` all the time. At least, that is how it is in the typescript implementation. I think it should be possible to have arbitrary (unspec'd) `application/json` response endpoints.

**Comment by snarfed** [comment]
Sure! You know best, happy to update this PR or close, whichever's easiest.

**Comment by bnewbold** [comment]
I pulled in your commit to retain history (thanks for the catch/contribution!), but am closing this in favor of https://github.com/bluesky-social/atproto-website/pull/177 (some tweaking of language). Appologies if there was a more elegant git/github way to wrangle this.

**Comment by snarfed** [comment]
Hey, sounds great! I'm not at all worried about git credit, but thank you, appreciate it. Glad to see the update.

**Pull request closed without merging**
